baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Italian Notes'
theme = 'yinyang'

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
headTitle = "Learning Italian"
description = "An English Speaker's Personal Study Notes"
mainSections = ["posts"]
extraCSSFiles = ["css/site.css"]
